/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./src/**/*.{html,ts}"],
  theme: {
    extend: {
      colors: {
        /* Dark navy brand background */
        background: "#02151f",

        /* Primary — soft ice-blue */
        primary: "#a4cce5",
        "primary-deep": "#0a2019",
        "primary-container": "#0c3a4e",
        "on-primary": "#033448",
        "on-primary-container": "#7da4bc",
        "primary-fixed": "#c3e8ff",
        "primary-fixed-dim": "#a4cce5",
        "on-primary-fixed": "#001e2c",
        "on-primary-fixed-variant": "#224b60",
        "inverse-primary": "#3c6379",

        /* Secondary — bright cyan accent */
        secondary: "#5de6ff",
        "secondary-container": "#00cbe6",
        "on-secondary": "#00363e",
        "on-secondary-container": "#00515d",
        "secondary-fixed": "#a2eeff",
        "secondary-fixed-dim": "#2fd9f4",
        "on-secondary-fixed": "#001f25",
        "on-secondary-fixed-variant": "#004e5a",

        /* Tertiary — muted slate-blue */
        tertiary: "#aecade",
        "tertiary-container": "#1d3949",
        "on-tertiary": "#173343",
        "on-tertiary-container": "#87a3b5",
        "tertiary-fixed": "#cae6fb",
        "tertiary-fixed-dim": "#aecade",
        "on-tertiary-fixed": "#001e2d",
        "on-tertiary-fixed-variant": "#2f4a5a",

        /* Surfaces — navy family */
        surface: "#02151f",
        "surface-dim": "#02151f",
        "surface-bright": "#293c47",
        "surface-container-lowest": "#001019",
        "surface-container-low": "#0a1e28",
        "surface-container": "#0e222c",
        "surface-container-high": "#192c37",
        "surface-container-highest": "#243742",
        "surface-variant": "#243742",
        "on-surface": "#d1e5f3",
        "on-surface-variant": "#c1c7cc",
        "inverse-surface": "#d1e5f3",
        "inverse-on-surface": "#20333d",
        outline: "#8b9196",
        "outline-variant": "#41484c",
        "surface-tint": "#a4cce5",

        /* Error */
        error: "#ffb4ab",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",

        /* Legacy green ramp (kept for existing helpers) */
        forest: "#1b4332",
        moss: "#2d6a4f",
        leaf: "#52b788",
        mint: "#cce9dc",
        bone: "#eef4f1",
        "mint-50": "#f2f7f4",
        "mint-100": "#e4ede7",
        "mint-200": "#cce0d6",
        "mint-300": "#d5e3dc",
        "mint-400": "#dce9e2",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        margin: "2rem",
        "margin-mobile": "1rem",
        "margin-desktop": "3rem",
        gutter: "1.5rem",
        "gutter-mobile": "1rem",
        "gutter-desktop": "2.5rem",
        "gutter-lg": "2rem",
        "gutter-sm": "1rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
      },
      fontFamily: {
        display: ["Space Grotesk", "system-ui", "sans-serif"],
        sans: ["Space Grotesk", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "ui-monospace", "monospace"],
        hebrew: ['"Frank Ruhl Libre"', "serif"],
        "headline-sm": ["Space Grotesk", "system-ui", "sans-serif"],
        "headline-md": ["Space Grotesk", "system-ui", "sans-serif"],
        "headline-lg": ["Space Grotesk", "system-ui", "sans-serif"],
        "headline-lg-mobile": ["Space Grotesk", "system-ui", "sans-serif"],
        "display-mobile": ["Space Grotesk", "system-ui", "sans-serif"],
        "body-sm": ["Inter", "system-ui", "sans-serif"],
        "body-md": ["Inter", "system-ui", "sans-serif"],
        "body-lg": ["Inter", "system-ui", "sans-serif"],
        "code-sm": ["JetBrains Mono", "ui-monospace", "monospace"],
        "code-lg": ["JetBrains Mono", "ui-monospace", "monospace"],
        "label-caps": ["JetBrains Mono", "ui-monospace", "monospace"],
      },
      fontSize: {
        display: ["56px", { lineHeight: "64px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "display-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-sm": ["18px", { lineHeight: "26px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "26px", letterSpacing: "0em", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "22px", letterSpacing: "0em", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "18px", letterSpacing: "0em", fontWeight: "400" }],
        "code-lg": ["14px", { lineHeight: "22px", letterSpacing: "0em", fontWeight: "500" }],
        "code-sm": ["12px", { lineHeight: "18px", letterSpacing: "0em", fontWeight: "500" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "600" }],
        "label-code": ["0.75rem", { lineHeight: "1rem", letterSpacing: "0.06em", fontWeight: "400" }],
        "label-micro": ["0.6875rem", { lineHeight: "0.875rem", letterSpacing: "0.08em", fontWeight: "500" }],
      },
      keyframes: {
        "rise-in": {
          from: { opacity: "0", transform: "translateY(16px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        marquee: {
          from: { transform: "translateX(0)" },
          to: { transform: "translateX(-50%)" },
        },
      },
      animation: {
        "rise-in": "rise-in 1s cubic-bezier(0.2, 0.7, 0.3, 1) both",
      },
    },
  },
  plugins: [],
};